openapi: 3.0.3
info:
    title: Word of Wosdom
    description: RESTful API for Word of Wisdom service.
    version: "1.0"
servers:
    - url: https://localhost:8080/words
paths:
    /words:
        get:
            tags:
                - words
            summary: Request for new quote, returns task
            description: First step for new quote, returns task
            operationId: words#request
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/WordsTask'
                            example:
                                difficulty: 4
                                hash: 006b848c0e6dc6f33b76ec211a7405a5e64d2889df511b8188f1489612bfabc2
                "400":
                    description: 'bad_request: is a common error response for bad request'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BadRequestError'
                            example:
                                attributes: '{"entityId":"xxxx-xxxx-xxxx-xxxx"}'
                                msg: JWT token has expired.
                                msgCode: JWT_TOKEN_EXPIRED
                "401":
                    description: Unauthorized response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/WordsTask'
                            example:
                                difficulty: 4
                                hash: 006b848c0e6dc6f33b76ec211a7405a5e64d2889df511b8188f1489612bfabc2
                "403":
                    description: Forbidden response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/WordsTask'
                            example:
                                difficulty: 4
                                hash: 006b848c0e6dc6f33b76ec211a7405a5e64d2889df511b8188f1489612bfabc2
                "500":
                    description: 'internal: is a common error response for internal error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InternalError'
                            example:
                                attributes: '{"entityId":"xxxx-xxxx-xxxx-xxxx"}'
                                msg: JWT token has expired.
                                msgCode: JWT_TOKEN_EXPIRED
        post:
            tags:
                - words
            summary: Return smartypents quote
            description: Returns smartypents quote
            operationId: words#words
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/WordsRequestBody'
                        example:
                            solution: Molestias quo.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/WordsResult'
                            example:
                                quote: Life is too short to remove USB safely
                "400":
                    description: 'bad_request: is a common error response for bad request'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BadRequestError'
                            example:
                                attributes: '{"entityId":"xxxx-xxxx-xxxx-xxxx"}'
                                msg: JWT token has expired.
                                msgCode: JWT_TOKEN_EXPIRED
                "403":
                    description: Forbidden response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/WordsResult'
                            example:
                                quote: Life is too short to remove USB safely
                "500":
                    description: 'internal: is a common error response for internal error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InternalError'
                            example:
                                attributes: '{"entityId":"xxxx-xxxx-xxxx-xxxx"}'
                                msg: JWT token has expired.
                                msgCode: JWT_TOKEN_EXPIRED
components:
    schemas:
        BadRequestError:
            type: object
            properties:
                attributes:
                    type: string
                    description: Message attributes
                    example: '{"entityId":"xxxx-xxxx-xxxx-xxxx"}'
                    format: binary
                msg:
                    type: string
                    description: Detailed error message
                    example: JWT token has expired.
                msgCode:
                    type: string
                    description: Key to select a localized message
                    example: JWT_TOKEN_EXPIRED
            description: is a common error response for bad request
            example:
                attributes: '{"entityId":"xxxx-xxxx-xxxx-xxxx"}'
                msg: JWT token has expired.
                msgCode: JWT_TOKEN_EXPIRED
            required:
                - msg
                - msgCode
        InternalError:
            type: object
            properties:
                attributes:
                    type: string
                    description: Message attributes
                    example: '{"entityId":"xxxx-xxxx-xxxx-xxxx"}'
                    format: binary
                msg:
                    type: string
                    description: Detailed error message
                    example: JWT token has expired.
                msgCode:
                    type: string
                    description: Key to select a localized message
                    example: JWT_TOKEN_EXPIRED
            description: is a common error response for internal error
            example:
                attributes: '{"entityId":"xxxx-xxxx-xxxx-xxxx"}'
                msg: JWT token has expired.
                msgCode: JWT_TOKEN_EXPIRED
            required:
                - msg
                - msgCode
        WordsRequestBody:
            type: object
            properties:
                solution:
                    type: string
                    description: Solution block
                    example: Unde velit delectus.
            example:
                solution: Quos voluptatem nulla et harum laborum aperiam.
        WordsResult:
            type: object
            properties:
                quote:
                    type: string
                    description: Words of wisdome
                    example: Life is too short to remove USB safely
            example:
                quote: Life is too short to remove USB safely
        WordsTask:
            type: object
            properties:
                difficulty:
                    type: integer
                    description: Target difficulty
                    example: 4
                    format: int64
                hash:
                    type: string
                    description: Previous hash
                    example: 006b848c0e6dc6f33b76ec211a7405a5e64d2889df511b8188f1489612bfabc2
            example:
                difficulty: 4
                hash: 006b848c0e6dc6f33b76ec211a7405a5e64d2889df511b8188f1489612bfabc2
tags:
    - name: words
